AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for deploying FastAPI backend with Elastic Beanstalk

Parameters:
  ApplicationName:
    Description: Name of the Elastic Beanstalk application.
    Type: String
    Default: FastAPIApp
  EnvironmentName:
    Description: Name of the Elastic Beanstalk environment.
    Type: String
    Default: FastAPIEnv
  S3Bucket:
    Description: S3 bucket where the FastAPI source bundle is stored.
    Type: String
  S3Key:
    Description: S3 key (path) for the FastAPI source bundle ZIP file.
    Type: String
  SolutionStackName:
    Description: The solution stack to use.
    Type: String
    Default: "64bit Amazon Linux 2 v5.4.7 running Python 3.8"
  VersionLabel:
    Description: The application version label.
    Type: String
    Default: v1
  MONGO_URI:
    Description: MongoDB connection string.
    Type: String

Resources:
  FastAPIApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: "FastAPI Application"

  FastAPIApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref FastAPIApplication
      Description: "Version of FastAPI Application"
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key

  FastAPIEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref FastAPIApplication
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: !Ref SolutionStackName
      VersionLabel: !Ref VersionLabel
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENVIRONMENT
          Value: "production"
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: MONGO_URI
          Value: !Ref MONGO_URI

Outputs:
  EnvironmentURL:
    Description: URL of the Elastic Beanstalk environment.
    Value: !GetAtt FastAPIEnvironment.EndpointURL
