AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template that creates all necessary resources for deploying a FastAPI
  backend on Elastic Beanstalk using EC2 (Python platform). This template provisions:
    - IAM roles and instance profile for EB EC2 instances
    - IAM role for the EB service
    - The EB Application, ApplicationVersion, and Environment

Parameters:
  ApplicationName:
    Description: Name of the Elastic Beanstalk application.
    Type: String
    Default: FastAPIApp
  EnvironmentName:
    Description: Name of the Elastic Beanstalk environment.
    Type: String
    Default: FastAPIEnv
  S3Bucket:
    Description: S3 bucket where the FastAPI source bundle (ZIP file) is stored.
    Type: String
  S3Key:
    Description: S3 key (path) for the FastAPI source bundle ZIP file.
    Type: String
  SolutionStackName:
    Description: The solution stack (platform) to use.
    Type: String
    Default: "64bit Amazon Linux 2023 v4.4.1 running Python 3.9"
  MONGOURI:
    Description: MongoDB connection string.
    Type: String

Resources:
  # IAM Role for EC2 instances (for Elastic Beanstalk)
  EBEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-elasticbeanstalk-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier

  # Instance Profile for EC2 instances
  EBEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: aws-elasticbeanstalk-ec2-role
      Roles:
        - Ref: EBEc2Role

  # IAM Role for the Elastic Beanstalk service
  EBServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: aws-elasticbeanstalk-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - elasticbeanstalk.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService

  # Elastic Beanstalk Application
  FastAPIApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: "FastAPI Application"

  # Application version using the ZIP from S3
  FastAPIApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref FastAPIApplication
      Description: "Version of FastAPI Application"
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key

  # Elastic Beanstalk Environment
  FastAPIEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn: FastAPIApplicationVersion
    Properties:
      ApplicationName: !Ref FastAPIApplication
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: !Ref SolutionStackName
      # No se especifica VersionLabel para que EB use la última versión registrada
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENVIRONMENT
          Value: production
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: MONGO_URI
          Value: !Ref MONGOURI
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: WEB_BIND
          Value: 0.0.0.0:8080
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: HOST
          Value: 0.0.0.0
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: PORT
          Value: 8080
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref EBEc2InstanceProfile
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref EBServiceRole

Outputs:
  EnvironmentURL:
    Description: "URL of the Elastic Beanstalk environment."
    Value: !GetAtt FastAPIEnvironment.EndpointURL
