AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template for deploying a CloudFront distribution for the Next.js frontend.
  This template assumes that the S3 bucket for static hosting already exists.

Parameters:
  BucketName:
    Description: "Name of the existing S3 bucket that hosts the static frontend"
    Type: String
  PriceClass:
    Description: "CloudFront Price Class (PriceClass_100, PriceClass_200, or PriceClass_All)"
    Type: String
    Default: PriceClass_100

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: FrontendS3Origin
            DomainName: !Sub "${BucketName}.s3.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: !Ref PriceClass
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  DistributionID:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
  DistributionDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
