AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template for deploying a CloudFront distribution for the Next.js frontend.
  This template creates (o utiliza) an S3 bucket for static hosting and a CloudFront distribution.

Parameters:
  BucketName:
    Description: "Name of the S3 bucket to host the static frontend (if it doesn't exist, it will be created)."
    Type: String
  PriceClass:
    Description: "CloudFront Price Class (PriceClass_100, PriceClass_200, or PriceClass_All)"
    Type: String
    Default: PriceClass_100

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: FrontendS3Origin
            DomainName: !GetAtt FrontendBucket.DomainName
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: !Ref PriceClass
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  DistributionID:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
  DistributionDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
