name: Deploy Back-End to AWS

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy CloudFormation Stack for FastAPI
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/backend-cloudformation.yaml \
            --stack-name FastAPIStack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides "MONGOURI=${{ secrets.MONGOURI }}" "S3Bucket=btg-fastapi-deploy" "S3Key=backend-app.zip"
      

      
