name: Deploy Back-End to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Package FastAPI App
        id: package
        run: |
          TIMESTAMP=$(date +%s)
          zip -r backend-app-${TIMESTAMP}.zip backend/
          echo "::set-output name=zip_name::backend-app-${TIMESTAMP}.zip"

      - name: Upload package to S3
        run: |
          aws s3 cp ${{ steps.package.outputs.zip_name }} s3://btg-fastapi-deploy/${{ steps.package.outputs.zip_name }} --region us-east-2

      - name: Deploy CloudFormation Stack for FastAPI
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/backend-cloudformation.yaml \
            --stack-name FastAPIStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides "MONGOURI=${{ secrets.MONGOURI }}" "S3Bucket=btg-fastapi-deploy" "S3Key=${{ steps.package.outputs.zip_name }}" \
            --region us-east-2
